# Generated by Django 3.2.4 on 2022-09-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
