# Generated by Django 3.2.4 on 2022-09-26 09:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
