# Generated by Django 3.2.4 on 2022-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../avatar_hrwoqk.png', upload_to='images/'),
        ),
    ]
