# Generated by Django 3.2.15 on 2022-09-12 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_of_property', models.CharField(choices=[('detached_house', 'Detached House'), ('terrace_house', 'Terrace House'), ('apartment', 'Apartment'), ('semi_detached', 'Semi-detached'), ('bungalows', 'Bungalows')], max_length=15)),
                ('bedrooms', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('commerce_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], max_length=15)),
                ('image_one', models.ImageField(default='../Default_Image_Thumbnail_loxqet.png', upload_to='images/')),
                ('image_two', models.ImageField(default='../Default_Image_Thumbnail_loxqet.png', upload_to='images/')),
                ('image_three', models.ImageField(default='../Default_Image_Thumbnail_loxqet.png', upload_to='images/')),
                ('image_four', models.ImageField(default='../Default_Image_Thumbnail_loxqet.png', upload_to='images/')),
                ('image_five', models.ImageField(default='../Default_Image_Thumbnail_loxqet.png', upload_to='images/')),
                ('image_six', models.ImageField(default='../Default_Image_Thumbnail_loxqet.png', upload_to='images/')),
                ('image_seven', models.ImageField(default='../Default_Image_Thumbnail_loxqet.png', upload_to='images/')),
                ('image_eight', models.ImageField(default='../Default_Image_Thumbnail_loxqet.png', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
