# Generated by Django 3.2.4 on 2022-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_eight',
            field=models.ImageField(default='../Placeholder-Clipart-Icon_dhzywt.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_five',
            field=models.ImageField(default='../Placeholder-Clipart-Icon_dhzywt.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_four',
            field=models.ImageField(default='../Placeholder-Clipart-Icon_dhzywt.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_one',
            field=models.ImageField(default='../Placeholder-Clipart-Icon_dhzywt.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_seven',
            field=models.ImageField(default='../Placeholder-Clipart-Icon_dhzywt.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_six',
            field=models.ImageField(default='../Placeholder-Clipart-Icon_dhzywt.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_three',
            field=models.ImageField(default='../Placeholder-Clipart-Icon_dhzywt.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_two',
            field=models.ImageField(default='../Placeholder-Clipart-Icon_dhzywt.png', upload_to='images/'),
        ),
    ]
